package main

import (
  "os"
  "bufio"
  "fmt"
  "strings"
  "log"
  "github.com/brothertoad/tags"
)

// Test program for the tag module.  Input can be either a flac file, an mp3 file,
// an m4a file, or a list file.  A list file contains a list of audio files,
// one per line, such as generated by the find command.

func main() {
  for j:= 1; j < len(os.Args); j++ {
    path := os.Args[j]
    if strings.HasSuffix(path, "list") {
      file, err := os.Open(path)
      if err != nil {
        log.Fatal(err)
      }
      defer file.Close()
      scanner := bufio.NewScanner(file)
      for scanner.Scan() {
        dumpFile(scanner.Text())
      }
      if err := scanner.Err(); err != nil {
        log.Fatal(err)
      }
    } else {
      dumpFile(path)
    }
  }
}

func dumpFile(path string) {
  m := tags.GetTagsFromFile(path)
  fmt.Printf("file %s has %d tags\n", path, len(m))
  for key, value := range m {
    fmt.Printf("%s: %s\n", key, value)
  }
}
